version: '3.4'

services:
  mongodb_container:
    image: mongo    
    environment:
      MONGO_INITDB_DATABASE: ProductsProtective
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: