version: '3.4'


services:
  protectivewearproducts:
    image: protectivewearproducts:latest
    depends_on:
      - "mongo"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=https://+:443;http://+:80
       - ASPNETCORE_HTTPS_PORT=44364
       - ASPNETCORE_Kestrel__Certificates__Default__Password=7713Gil
       - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ProtectiveWearSecurity.pfx
       - ProductsDatabaseSettings__Host=mongo
    volumes:
      - ./https/ProtectiveWearSecurity.pfx:/https/ProtectiveWearSecurity.pfx:ro
      

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - db_volume:/var/lib/mongo/data

volumes:
  db_volume:
   
  